# Generated by Django 4.2 on 2025-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_rating_unique_together_rating_rated_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AR', 'Author'), ('UR', 'User'), ('GD', 'Guide')], default='UR', max_length=2),
        ),
    ]
