# Generated by Django 4.2 on 2025-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_counts',
            field=models.IntegerField(default=0),
        ),
    ]
