from decouple import config

DATABASE_NAME = config('DATABASE_NAME')
DATABASE_USER = config('DATABASE_USER')
DATABASE_PASSWORD = config('DATABASE_PASSWORD')

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = 'adilaralbaev00@gmail.com'
EMAIL_HOST_PASSWORD = 'ivjt qriv sryr atzg'
EMAIL_PORT = 587

BOT = config('BOT')

CLOUD_NAME = config('CLOUD_NAME')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET')

STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')