services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tik_tok_tour_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kukushonok
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
      - static:/app/static
      - static_volume:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - POSTGRES_DB=tik_tok_tour_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kukushonok
      - DJANGO_SETTINGS_MODULE=my_project.settings

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

#  bot:
#    build: .
#    container_name: telegram_bot
#    depends_on:
#      - redis
#      - web
#    command: [ "python", "tg_bot.py" ]
#
#    restart: always
#
#    environment:
#      - POSTGRES_DB=tour_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=kukushonok
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DJANGO_SETTINGS_MODULE=tour.settings
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static_volume:/app/staticfiles
      - media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  static_volume:
  media:


