# Generated by Django 4.2 on 2025-07-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_remove_tour_users_like_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('available_slots', models.PositiveIntegerField()),
                ('duration_days', models.IntegerField(default=1)),
                ('collection_point', models.CharField(max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tour.tour')),
            ],
            options={
                'unique_together': {('tour', 'date')},
            },
        ),
    ]
