# Generated by Django 4.2 on 2025-07-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour_rating_counts_tourdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='level',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], default='Easy', max_length=6),
        ),
    ]
