# Generated by Django 4.2 on 2025-07-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_tour_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
