# Generated by Django 5.2.4 on 2025-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.FileField(upload_to='tour_images/'),
        ),
    ]
