# Generated by Django 5.2.4 on 2025-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
    ]
